severity: error

linters:

  BorderZero:
    enabled: true
    convention: zero

  BemDepth:
    enabled: true

  ColorKeyword:
    enabled: false

  ColorVariable:
    enabled: false

  DeclarationOrder:
    enabled: false

  ExtendDirective:
    enabled: true

  LeadingZero:
    enabled: false

  NameFormat:
    enabled: true

  NestingDepth:
    severity: warning
    enabled: true
    max_depth: 3
    ignore_parent_selectors: false

  PrivateNamingConvention:
    enabled: true
    prefix: _

  PropertySortOrder:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorDepth:
    severity: warning
    enabled: true
    max_depth: 3

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
    class_convention: ^(?!js-).*
    class_convention_explanation: should not be written in the form js-*

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SingleLinePerSelector:
    enabled: false

  StringQuotes:
    enabled: true
    style: double_quotes

  UnnecessaryMantissa:
    enabled: false

  ZeroUnit:
    enabled: false
